# Generated by Django 6.0 on 2025-12-16 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='project_image',
            new_name='product_img',
        ),
    ]
